backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: technologiestiftung/design-system
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: 'doc'
    label: 'Doc'
    folder: '_docs/doc'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
